services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: nequi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/nequi
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: admin
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/nequi
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge