urldatabase: ${URL_DATABASE}

server:
  port: ${PORT:8080}

spring:
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: r2dbc:${DATABASE_URL}
  flyway:
    url: jdbc:${DATABASE_URL}