urldatabase: ${URL_DATABASE}

server:
  port: ${PORT:8080}

spring:
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: r2dbc:${URL_DATABASE}?sslmode=require
  flyway:
    url: jdbc:${URL_DATABASE}