urldatabase: ${URL_DATABASE}

server:
  port: ${PORT:8080}

spring:
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: r2dbc:${URL_DATABASE}
  flyway:
    url: jdbc:postgresql://c5flugvup2318r.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dfnpu1ro7c55vd